SELECT P.PRODUCT_ID, P.PRODUCT_NAME, AMOUNT * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER 
    WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE <= '2022-05-31'
    GROUP BY PRODUCT_ID
) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;