SELECT 
    CRH.HISTORY_ID, 
    ROUND(DAILY_FEE * CRH.DATE * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM (
    SELECT RH.HISTORY_ID, C.CAR_TYPE, C.DAILY_FEE,
    DATEDIFF(END_DATE, START_DATE) + 1 AS DATE,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
    ON C.CAR_ID = RH.CAR_ID
    WHERE CAR_TYPE = '트럭'
) AS CRH
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON CRH.CAR_TYPE = P.CAR_TYPE AND CRH.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;