SELECT AP.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AS AP
JOIN PATIENT AS P ON AP.PT_NO = P.PT_NO
JOIN DOCTOR AS D ON AP.MDDR_ID = D.DR_ID
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
AND APNT_CNCL_YMD IS NULL
AND AP.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC;