WITH RECURSIVE hours AS (
    SELECT 0 AS hour
    UNION ALL
    SELECT hour + 1 FROM hours WHERE hour < 23
)
SELECT H.hour, IFNULL(AO.COUNT, 0) AS 'COUNT'
FROM hours AS H
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS 'COUNT'
    FROM ANIMAL_OUTS
    GROUP BY HOUR
) AS AO
ON H.hour = AO.HOUR
ORDER BY HOUR ASC